### ISSUE TITLE
Cannot Compile Code for Upload to Arduino UNO

### ISSUE THREAD

**Issue by RKF-FKR** [maximevince/arduinix_gps_timer_isr#1]
Hello,

Tried multiple attempts to compile, however hangs - with various errors such as

In function 'void timerIsr()'
'day' was not declared in this scope
'hour' was not declared in this scope
'minute' was not declared in this scope

gps_handler.ino: In function 'void GPSLoop()':
gps_handler:59:11: error: 'setTime' was not declared in this scope

There are others, but I suspect that there is some files missing

**Comment by maximevince** [comment]
Hi @RKF-FKR, thanks for you interest in the project.

It's been a while since I've compiled this myself. I just tried compiling it again with Arduino IDE 1.8.15, for board "Arduino Uno", and that works.

Can you give a little more details about which target you're trying to compile for, and which version of the Arduino IDE you're using?

I've included the correct library version in the source code repo, but maybe they're conflicting with some version you have installed locally? (Not sure, it's been a while :))
The versions included are:
- NeoGPS 4.1.3
- Time 1.5
- TimerOne: version unknown; this seems pretty old

**Comment by RKF-FKR** [comment]
Hello Maxime,

Thanks so much for your reply - I’ve been sweating on hearing back for you.  I’m pleased you took the time to reply. 

I’ve been working on solving it today (when your message arrived) with no luck

I even reverted the Arduino software version to the date of your files with no luck either.
Currently using the same Arduino release as you.
I’m trying to compile for a standard Arduino Uno, which is used with the Arduinix project.


I've tried 
Time 1.5 (and every other one I could find)
TimerOne (V1.1 I think, But I tried them all)
NeoGPS 4.1.3 

I would be grateful if you could please compile for the above two time zones.
If you could please compile for two time zones: here in Australia we are TZ 11 (normal) and TZ 12 (during daylight savings).

I really appreciate you replying.

Rod F

**Comment by maximevince** [comment]
Hi Rod,

I'm afraid it'd be better if you could create your own build. That way you can make the modifications you need (and maybe send a pull request :) )
For instance: I remember that after a while the internal clock of the Arduino started drifting, and would require a new GPS time sync. Something that's not in the project yet, but should be added.

Anyway, could you provide more information about the error messages you're getting? E.g. a screenshot, or the compiler output in the window. Please set "Show verbose output" for "compilation" in the preferences.

Are you on Linux/Windows/OSX?

**Comment by RKF-FKR** [comment]
Hello Maxime.

Understood.
I'm Using MacOs High Sierra
Here is the verbose error output
[Verbose Compile Errors.txt](https://github.com/maximevince/arduinix_gps_timer_isr/files/6527901/Verbose.Compile.Errors.txt)

Additionally here is a compile error list from a fresh install into an old Win7 machine.  Same issues encountered.
[Windows7 Compile Errors.txt](https://github.com/maximevince/arduinix_gps_timer_isr/files/6527925/Windows7.Compile.Errors.txt)

**Comment by maximevince** [comment]
Hi @RKF-FKR,

That was useful, thanks. I reproduced the issue on a Windows10 build.
Can you verify that the patch I just pushed to master solves your issue?

Cheers,
Maxime

**Comment by RKF-FKR** [comment]
Hello Maxime - that has solved the problem.  The compile was successful.  
My sincere thanks.
I will continue to follow your releases in case you decide to include the time re-sync feature in a future update.  Sadly I don't have the coding skills to do it myself.

**Comment by maximevince** [comment]
@RKF-FKR,

I have pushed another commit to add proper timezone handling w/ DST.
You'll need to change the timezone config in `arduinix_gps_timer_isr.ino` lines 27-30 according to your timezone.

Also, I noticed that the clock drift issue was already solved in an earlier commit :)
It will re-sync with GPS time at most once per hour, whenever a valid time+date fix is available.

**Comment by RKF-FKR** [comment]
Hello Maxime - all seems to be well - I'm getting the GPS loading bars, however I think a have a newer SPI GPS shield that lacks the required breakout pins for CSn and Reset.  Could you please share the GPS module that you used so I can buy the same?  I'm using the Keyestudio GPS shield that plugs directly into the SPI port on the UNO but I do not think the ublox NEO6m has these pins anymore 
link: https://www.u-blox.com/sites/default/files/products/documents/NEO-6_DataSheet_%28GPS.G6-HW-09005%29.pdf
