### ISSUE TITLE
Time flickering, multiple numbers illuminated in each nixie

### ISSUE THREAD

**Issue by RKF-FKR** [maximevince/arduinix_gps_timer_isr#2]
Hello Maxime

I purchased a Sparkfun ZOE-M8Q, (GPS-15193) that has the necessary breakout pins for this project.

GPS Connected: 
3V, GND
MOSI, MISO, CLK on the ICSP connector
RST to A4 
CS to A5.

Enabled GPS Debug in your sketch - OK
Startup progress bars as expected (right to left)
GPS time acquisition now shows in the serial monitor.  
Sketch then updates nixies to show time.

Now the issues

(1) I can see the time in the display, but other digits are illuminated at the same time.  
(2) The seconds are impossible to read because most are lit, but I would say that they are pulsing/alternating between “55” and “66”
(3) The entire display ‘pulses’ every second in time with the second.
(4) The first hour digit is faint.

Steps attempted to rectify.

Changed libraries from most recent, to the supplied libraries on your GitHub .
Changed tube_delay in steps from 1 (solid all digits) through to 15 (unreadable flickering) without improvement.
Changed from my 6 digit display to 4 digit spare display with the same result.

The default poor timekeeping sketch supplied by Arduinix loads and works and also displays without any of the above flickering etc.

I wonder if you have any ideas?  Perhaps the RST can be wired to the ICSP reset pin.  Maybe the pulsing is happening because the GPS is not resetting and leaking through causing the display pulsing.
Perhaps the tube delay can be tested differently, by uncommenting the delay in each “case” of the tube handler page and choosing different delays?

Thanks in advance.

**Comment by maximevince** [comment]
* Did you manage to solve the issue?
* What Arduino board are you testing this on?  
 As mentioned in the README, timings have only been verified on ATMEGA 2560.
 Changes to the ISR/timer routines might be needed for it to work on different MCUs.

**Comment by RKF-FKR** [comment]
Sadly I did not manage to get it working.  I tried many times with many edits without success.  In the end I gave up.  
I was using only the Arduino Uno, so that will likely be the issue.  I will buy one of the 2560 and try again.  (I also need to buy some more nixies, because I used them on another project)
Thank you for your response.
